export const ACTIONS = {
    GET_USER_DATA_REQUEST: "GET_USER_DATA_REQUEST",
    GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
    GET_USER_REPOSITORIES_REQUEST: 'GET_USER_REPOSITORIES_REQUEST',
    GET_USER_REPOSITORIES_SUCCESS: 'GET_USER_REPOSITORIES_SUCCESS'
}
